import type { SocioListItem, SocioDetalle } from "@/app/dashboard/socios/actions";

export const MOCK_USUARIO = {
  logueado: true,
  nombre: "Juan Pérez",
  rol: "admin",
};

export const MOCK_SOCIOS: SocioListItem[] = [
  {
    id: "1",
    nombre: "Juan",
    apellido: "Pérez",
    nroDocumento: "12345678",
    obraSocial: "PAMI",
    plan: "A",
    estado: "Activo",
  },
  {
    id: "2",
    nombre: "María",
    apellido: "Gómez",
    nroDocumento: "20123456",
    obraSocial: "OSDE",
    plan: "B",
    estado: "Activo",
  },
  {
    id: "3",
    nombre: "Carlos",
    apellido: "Rodríguez",
    nroDocumento: "34567890",
    obraSocial: "IAPOS",
    plan: "A",
    estado: "Baja",
  },
  {
    id: "4",
    nombre: "Ana",
    apellido: "Martínez",
    nroDocumento: "45678901",
    obraSocial: "PAMI",
    plan: "B",
    estado: "Activo",
  },
  {
    id: "5",
    nombre: "Roberto",
    apellido: "López",
    nroDocumento: "20345678",
    obraSocial: "Jerárquicos Salud",
    plan: "A",
    estado: "Activo",
  },
  {
    id: "6",
    nombre: "Laura",
    apellido: "Fernández",
    nroDocumento: "56789012",
    obraSocial: null,
    plan: "B",
    estado: "Baja",
  },
  {
    id: "7",
    nombre: "Diego",
    apellido: "García",
    nroDocumento: "67890123",
    obraSocial: "OSDE",
    plan: "A",
    estado: "Activo",
  },
  {
    id: "8",
    nombre: "Patricia",
    apellido: "Sánchez",
    nroDocumento: "78901234",
    obraSocial: "PAMI",
    plan: "B",
    estado: "Activo",
  },
  {
    id: "9",
    nombre: "Fernando",
    apellido: "Torres",
    nroDocumento: "20456789",
    obraSocial: "IAPOS",
    plan: "A",
    estado: "Baja",
  },
  {
    id: "10",
    nombre: "Verónica",
    apellido: "Ruiz",
    nroDocumento: "89012345",
    obraSocial: "Jerárquicos Salud",
    plan: "B",
    estado: "Activo",
  },
];

export const MOCK_SOCIOS_DETALLE: SocioDetalle[] = [
  {
    id: "1",
    nombre: "Juan",
    apellido: "Pérez",
    nroDocumento: "12345678",
    fechaNacimiento: "1990-01-01",
    sexo: "Hombre",
    ciudad: "Buenos Aires",
    calle: "Falsa",
    altura: "123",
    fechaAlta: "2024-01-01",
    obraSocial: "PAMI",
    nroAfiliadoObraSocial: "PAMI-12345678",
    plan: "A",
    sepelio: "SI",
    cobrador: "NO",
    observaciones: "Socio con domicilio particular en Buenos Aires.",
    telefonos: ["3412345678"],
    correos: ["juan.perez@example.com"],
    codeudores: [
      { id: "2", nombre: "María", apellido: "Gómez", nroDocumento: "20123456" },
    ],
  },
  {
    id: "2",
    nombre: "María",
    apellido: "Gómez",
    nroDocumento: "20123456",
    fechaNacimiento: "1985-05-15",
    sexo: "Mujer",
    ciudad: "Rosario",
    calle: "Córdoba",
    altura: "456",
    fechaAlta: "2023-06-12",
    obraSocial: "OSDE",
    nroAfiliadoObraSocial: "OSDE-20123456",
    plan: "B",
    sepelio: "NO",
    cobrador: "SI",
    telefonos: ["3418765432"],
    correos: ["maria.gomez@example.com"],
  },
  {
    id: "3",
    nombre: "Carlos",
    apellido: "Rodríguez",
    nroDocumento: "34567890",
    fechaNacimiento: "1962-11-20",
    sexo: "Hombre",
    ciudad: "Santa Fe",
    calle: "San Martín",
    altura: "789",
    fechaAlta: "2023-03-15",
    fechaBaja: "2024-12-01",
    obraSocial: "IAPOS",
    nroAfiliadoObraSocial: "IAPOS-34567890",
    plan: "A",
    sepelio: "SI",
    cobrador: "SI",
    telefonos: ["3421112233"],
    correos: ["carlos.rodriguez@example.com"],
  },
  {
    id: "4",
    nombre: "Ana",
    apellido: "Martínez",
    nroDocumento: "45678901",
    fechaNacimiento: "1978-08-08",
    sexo: "Mujer",
    ciudad: "Paraná",
    calle: "Urquiza",
    altura: "321",
    fechaAlta: "2024-06-01",
    obraSocial: "PAMI",
    nroAfiliadoObraSocial: "PAMI-45678901",
    plan: "B",
    sepelio: "SI",
    cobrador: "NO",
    observaciones: "Prefiere ser contactada por correo electrónico.",
    telefonos: ["3434445566"],
    correos: ["ana.martinez@example.com"],
  },
  {
    id: "5",
    nombre: "Roberto",
    apellido: "López",
    nroDocumento: "20345678",
    fechaNacimiento: "1970-03-22",
    sexo: "Hombre",
    ciudad: "Córdoba",
    calle: "Rivadavia",
    altura: "654",
    fechaAlta: "2022-09-10",
    obraSocial: "Jerárquicos Salud",
    nroAfiliadoObraSocial: "JS-20345678",
    plan: "A",
    sepelio: "SI",
    cobrador: "SI",
    telefonos: ["3517778899"],
    correos: ["roberto.lopez@example.com"],
  },
  {
    id: "6",
    nombre: "Laura",
    apellido: "Fernández",
    nroDocumento: "56789012",
    fechaNacimiento: "1995-12-30",
    sexo: "Otro",
    ciudad: "Rafaela",
    calle: "Belgrano",
    altura: "147",
    fechaAlta: "2024-02-20",
    fechaBaja: "2024-10-15",
    plan: "B",
    sepelio: "NO",
    cobrador: "NO",
    telefonos: ["3492223344"],
    correos: ["laura.fernandez@example.com"],
  },
  {
    id: "7",
    nombre: "Diego",
    apellido: "García",
    nroDocumento: "67890123",
    fechaNacimiento: "1988-07-14",
    sexo: "Hombre",
    ciudad: "Venado Tuerto",
    calle: "Mitre",
    altura: "258",
    fechaAlta: "2023-11-05",
    obraSocial: "OSDE",
    nroAfiliadoObraSocial: "OSDE-67890123",
    plan: "A",
    sepelio: "SI",
    cobrador: "NO",
    telefonos: ["3462556677"],
    correos: ["diego.garcia@example.com"],
  },
  {
    id: "8",
    nombre: "Patricia",
    apellido: "Sánchez",
    nroDocumento: "78901234",
    fechaNacimiento: "1973-04-05",
    sexo: "Mujer",
    ciudad: "Rosario",
    calle: "Oroño",
    altura: "951",
    fechaAlta: "2022-01-15",
    obraSocial: "PAMI",
    nroAfiliadoObraSocial: "PAMI-78901234",
    plan: "B",
    sepelio: "SI",
    cobrador: "SI",
    telefonos: ["3418889900", "3411122334"],
    correos: ["patricia.sanchez@example.com", "patricia@personal.com"],
  },
  {
    id: "9",
    nombre: "Fernando",
    apellido: "Torres",
    nroDocumento: "20456789",
    fechaNacimiento: "1965-09-18",
    sexo: "Hombre",
    ciudad: "Firmat",
    calle: "Sarmiento",
    altura: "753",
    fechaAlta: "2023-04-01",
    fechaBaja: "2024-06-30",
    obraSocial: "IAPOS",
    nroAfiliadoObraSocial: "IAPOS-20456789",
    plan: "A",
    sepelio: "SI",
    cobrador: "SI",
    telefonos: ["3464778899"],
    correos: ["fernando.torres@example.com"],
  },
  {
    id: "10",
    nombre: "Verónica",
    apellido: "Ruiz",
    nroDocumento: "89012345",
    fechaNacimiento: "1992-11-25",
    sexo: "Mujer",
    ciudad: "Cañada de Gómez",
    calle: "Buenos Aires",
    altura: "486",
    fechaAlta: "2024-08-12",
    obraSocial: "Jerárquicos Salud",
    nroAfiliadoObraSocial: "JS-89012345",
    plan: "B",
    sepelio: "NO",
    cobrador: "NO",
    observaciones: "Socio desde agosto de 2024.",
    telefonos: ["3471556677"],
    correos: ["veronica.ruiz@example.com"],
    codeudores: [
      { id: "1", nombre: "Juan", apellido: "Pérez", nroDocumento: "12345678" },
      { id: "4", nombre: "Ana", apellido: "Martínez", nroDocumento: "45678901" },
    ],
  },
];

export function getMockResponse(endpoint: string): unknown {
  if (endpoint === "/me" || endpoint.startsWith("/me")) {
    return { nombre: MOCK_USUARIO.nombre, rol: MOCK_USUARIO.rol };
  }
  if (endpoint === "/socios") {
    return MOCK_SOCIOS;
  }
  if (endpoint.startsWith("/socios/")) {
    const id = endpoint.split("/socios/")[1];
    const socio = MOCK_SOCIOS_DETALLE.find((s) => s.id === id);
    if (!socio) {
      throw new Error(`No hay mock definido para el socio con id: ${id}`);
    }
    return socio;
  }
  throw new Error(`No hay mock definido para el endpoint: ${endpoint}`);
}
